name: gokrazy CI

on:
  push:
  pull_request:

jobs:

  build:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        # Run on the latest stable Go version, e.g. 1.20.2:
        go-version: 'stable'
      id: go

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Build, Test and Create Disk Image
      run: |
        go install -mod=mod ./cmd/...
        go test -mod=mod -v ./...
